name: XML to BigTable Pipeline
description: A pipeline that reads payment transaction XML data, transforms it, and writes to BigTable

transforms:
  # Read from XML file
  - name: ReadFromXml
    type: ReadFromXml
    file_pattern: sample_data.xml
    record_element_tag: transaction
    include_attributes: true
    attribute_prefix: "@"
    outputs:
      - raw_transactions

  # Write raw data to file for inspection
  - name: WriteRawData
    type: WriteToText
    file_path_prefix: output/raw_transactions
    file_name_suffix: .json
    inputs:
      - raw_transactions

  # Enrich transaction data
  - name: EnrichTransactions
    type: Map
    fn_module: examples.xml_bigtable.utils
    fn_name: enrich_transaction_data
    inputs:
      - raw_transactions
    outputs:
      - enriched_transactions

  # Filter high-value transactions
  - name: FilterHighValueTransactions
    type: Filter
    fn_module: examples.xml_bigtable.utils
    fn_name: is_high_value_transaction
    inputs:
      - enriched_transactions
    outputs:
      - high_value_transactions

  # Write to BigTable
  - name: WriteToBigTable
    type: WriteToBigTableSimulator
    project_id: test-project
    instance_id: test-instance
    table_id: transactions
    column_family_id: transaction_data
    row_key_field: id
    batch_size: 100
    max_retries: 3
    skip_invalid_records: true
    inputs:
      - high_value_transactions
    outputs:
      - bigtable_output

  # Write results to file for inspection
  - name: WriteResults
    type: WriteToText
    file_path_prefix: output/high_value_transactions
    file_name_suffix: .json
    inputs:
      - high_value_transactions
